### ISSUE TITLE
Running casbin/casvisor panic on launch.

### ISSUE THREAD

**Issue by Leopere** [casdoor/awesome-auth#95]
This is running essentially in default I'm not certain how I've managed to get this to not work in basically default.  However, I haven't given it any config yet but that seems to be how this works for all I know according to the docs it seems it should work this way as far as I can tell.

```
 panic: unsupported driver name:
 
 goroutine 1 [running]:
 github.com/casvisor/casvisor/object.(*Adapter).open(0xc0002fc780)
 	/go/src/casvisor/object/adapter.go:86 +0x105
 github.com/casvisor/casvisor/object.NewAdapter({0x0, 0x0}, {0x0, 0x0})
 	/go/src/casvisor/object/adapter.go:65 +0x9a
 github.com/casvisor/casvisor/object.InitAdapter()
 	/go/src/casvisor/object/adapter.go:40 +0x49
 main.main()
 	/go/src/casvisor/main.go:30 +0x1d
```

```yaml
  casvisor:
    image: casbin/casvisor
    depends_on:
      - db
    environment:
      RUNNING_IN_DOCKER: "true"
    volumes:
      - /mnt/tank/persist/example.com/casvisor/production/conf:/home/casvisor/conf
    networks:
      - traefik
      - default
    deploy:
      update_config:
        order: stop-first
        failure_action: rollback
        delay: 30s
        parallelism: 1
      restart_policy:
        condition: on-failure
```
